name: Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # ручной запуск
  workflow_dispatch:

jobs:
  e2e:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout кода из репозитория
      - uses: actions/checkout@v4

      # 2. Настройка Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm install

      # 4. Установка Playwright
      - name: Install Playwright
        run: npx playwright install --with-deps

      # 5. Запуск тестов Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # 6. Сохранение отчетов Playwright
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results
          retention-days: 20

      # 7. Сохранение отчетов Allure
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      # 8. Забрать результаты предыдущего запуска
      - name: Checkout repository
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 9. Генерация Allure отчёта
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          keep_reports: 20
      # 10. Deploy отчёта
      - name: Deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Клонирование ветки gh-pages для получения истории (если существует)
      - name: Retrieve previous Allure history
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages || echo "gh-pages branch not found"
          if [ -d gh-pages/history ]; then
              echo "Copying history folder..."
              cp -R gh-pages/history ./allure-results/
          else
              echo "No history folder found."
          fi

      # 3. Настройка Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 4. Установка зависимостей
      - name: Install dependencies
        run: npm install

      # 5. Установка Playwright
      - name: Install Playwright
        run: npx playwright install

      # 6. Запуск тестов Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # 7. Генерация Allure отчёта, включая историю
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      # 8. Публикация отчёта на GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
